---
image:
  repository: lscr.io/linuxserver/radarr
  tag: 4.2.4.6635-ls157
  pullPolicy: IfNotPresent

env:
  TZ: Europe/London

persistence:
  config:
    enabled: true

service:
  main:
    ports:
      http:
        port: 7878
