---
apiVersion: v2
description: A common powered chart template. This can be useful for small projects that don't have their own chart.
name: app-template
version: 1.0.1
kubeVersion: ">=1.22.0-0"
maintainers:
  - name: ntrp
    email: me@ntrp.dev
dependencies:
  - name: common
    repository: https://ntrp.github.io/helm-charts
    version: 1.0.1
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: |
        **BREAKING**: Updated library version to 1.0.1.
      links:
        - name: Common library chart definition
          url: https://github.com/ntrp/helm-charts/blob/main/charts/library/common/Chart.yaml
