---
image:
  repository: lscr.io/linuxserver/sabnzbd
  tag: 3.7.0
  pullPolicy: IfNotPresent

persistence:
  config:
    enabled: true

service:
  main:
    ports:
      http:
        targetPort: 8080
