---
image:
  repository: lscr.io/linuxserver/jellyfin
  tag: 10.8.7-1-ls188
  pullPolicy: IfNotPresent

env:
  TZ: Europe/London

persistence:
  config:
    enabled: true

service:
  main:
    ports:
      http:
        port: 8096
