---
image:
  repository: cr.hotio.dev/hotio/readarr
  tag: latest
  pullPolicy: IfNotPresent

env:
  TZ: Europe/London

persistence:
  config:
    enabled: true

service:
  main:
    ports:
      http:
        port: 8787
